apiVersion: v1
kind: Service
metadata:
  name: {{ include "saas-app.fullname" . }}
  labels:
    {{- include "saas-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "saas-app.selectorLabels" . | nindent 4 }}
---
{{- if .Values.rollout.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "saas-app.fullname" . }}-canary
  labels:
    {{- include "saas-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "saas-app.selectorLabels" . | nindent 4 }}
{{- end }}
